app = "telegram-group-helper-bot"
primary_region = "iad" # Change to your preferred region
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  ENV = "production"
  WEBHOOK_PORT = "8080"

[mounts]
  source = "bot_data"
  destination = "/app/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/healthz"
  protocol = "http"
  timeout = 2000 